using System.Collections.Generic;

namespace HuntTrainRelay;

public enum HuntRank { B, A, S }

public record OtherRankMark(string Name, HuntRank Rank, string Expansion);

/// <summary>
/// B and S rank marks, by BNpcName id. These are deliberately kept apart from
/// ExpansionData (the A-ranks) because they are NOT part of a train: they exist
/// only to colour spawn points on the map and to drive optional chat echoes.
/// Nothing here ever reaches the train list or a report.
///
/// Sourced from Hunt Helper's bundled Data/*-B.json and *-S.json (MIT,
/// img02/HuntHelper). One entry there — Stolas, id 4367 — is listed as both A
/// and B rank; the A-rank definition wins, so it's excluded here.
/// </summary>
public static class OtherRankData
{
    public static readonly Dictionary<uint, OtherRankMark> ByNameId = new()
    {
        [2923] = new("Sewer Syrup", HuntRank.B, "ARR"),
        [2924] = new("Ovjang", HuntRank.B, "ARR"),
        [2925] = new("Gatling", HuntRank.B, "ARR"),
        [2926] = new("Albin the Ashen", HuntRank.B, "ARR"),
        [2927] = new("Flame Sergeant Dalvag", HuntRank.B, "ARR"),
        [2919] = new("White Joker", HuntRank.B, "ARR"),
        [2920] = new("Stinging Sophie", HuntRank.B, "ARR"),
        [2921] = new("Monarch Ogrefly", HuntRank.B, "ARR"),
        [2922] = new("Phecda", HuntRank.B, "ARR"),
        [2928] = new("Skogs Fru", HuntRank.B, "ARR"),
        [2929] = new("Barbastelle", HuntRank.B, "ARR"),
        [2930] = new("Bloody Mary", HuntRank.B, "ARR"),
        [2931] = new("Dark Helmet", HuntRank.B, "ARR"),
        [2932] = new("Myradrosh", HuntRank.B, "ARR"),
        [2933] = new("Vuokho", HuntRank.B, "ARR"),
        [2934] = new("Naul", HuntRank.B, "ARR"),
        [2935] = new("Leech King", HuntRank.B, "ARR"),
        [2953] = new("Laideronnette", HuntRank.S, "ARR"),
        [2954] = new("Wulgaru", HuntRank.S, "ARR"),
        [2955] = new("Mindflayer", HuntRank.S, "ARR"),
        [2956] = new("Thousand-cast Theda", HuntRank.S, "ARR"),
        [2957] = new("Zona Seeker", HuntRank.S, "ARR"),
        [2958] = new("Brontes", HuntRank.S, "ARR"),
        [2959] = new("Lampalagua", HuntRank.S, "ARR"),
        [2960] = new("Nunyunuwi", HuntRank.S, "ARR"),
        [2961] = new("Minhocao", HuntRank.S, "ARR"),
        [2962] = new("Croque-mitaine", HuntRank.S, "ARR"),
        [2963] = new("Croakadile", HuntRank.S, "ARR"),
        [2964] = new("The Garlok", HuntRank.S, "ARR"),
        [2965] = new("Bonnacon", HuntRank.S, "ARR"),
        [2966] = new("Nandi", HuntRank.S, "ARR"),
        [2967] = new("Chernobog", HuntRank.S, "ARR"),
        [2968] = new("Safat", HuntRank.S, "ARR"),
        [2969] = new("Agrippa The Mighty", HuntRank.S, "ARR"),
        [4350] = new("Alteci", HuntRank.B, "Heavensward"),
        [4351] = new("Kreutzet", HuntRank.B, "Heavensward"),
        [4360] = new("Lycidas", HuntRank.B, "Heavensward"),
        [4361] = new("Omni", HuntRank.B, "Heavensward"),
        [4352] = new("Gnath Cometdrone", HuntRank.B, "Heavensward"),
        [4353] = new("Thextera", HuntRank.B, "Heavensward"),
        [4354] = new("Pterygotus", HuntRank.B, "Heavensward"),
        [4355] = new("False Gigantopithecus", HuntRank.B, "Heavensward"),
        [4357] = new("The Scarecrow", HuntRank.B, "Heavensward"),
        [4356] = new("Scitalis", HuntRank.B, "Heavensward"),
        [4358] = new("Squonk", HuntRank.B, "Heavensward"),
        [4359] = new("Sanu Vali of Dancing Wings", HuntRank.B, "Heavensward"),
        [4374] = new("Kaiser Behemoth", HuntRank.S, "Heavensward"),
        [4375] = new("Senmurv", HuntRank.S, "Heavensward"),
        [4376] = new("The Pale Rider", HuntRank.S, "Heavensward"),
        [4377] = new("Gandarewa", HuntRank.S, "Heavensward"),
        [4378] = new("Bird of Paradise", HuntRank.S, "Heavensward"),
        [4380] = new("Leucrotta", HuntRank.S, "Heavensward"),
        [6008] = new("Shadow-dweller Yamini", HuntRank.B, "Stormblood"),
        [6009] = new("Ouzelum", HuntRank.B, "Stormblood"),
        [6010] = new("Gwas-y-neidr", HuntRank.B, "Stormblood"),
        [6011] = new("Buccaboo", HuntRank.B, "Stormblood"),
        [6012] = new("Manes", HuntRank.B, "Stormblood"),
        [6013] = new("Kiwa", HuntRank.B, "Stormblood"),
        [6002] = new("Gauki Strongblade", HuntRank.B, "Stormblood"),
        [6003] = new("Guhuo Niao", HuntRank.B, "Stormblood"),
        [6004] = new("Deidar", HuntRank.B, "Stormblood"),
        [6005] = new("Gyorai Quickstrike", HuntRank.B, "Stormblood"),
        [6007] = new("Aswang", HuntRank.B, "Stormblood"),
        [6006] = new("Kurma", HuntRank.B, "Stormblood"),
        [5984] = new("Okina", HuntRank.S, "Stormblood"),
        [5985] = new("Gamma", HuntRank.S, "Stormblood"),
        [5986] = new("Orghana", HuntRank.S, "Stormblood"),
        [5987] = new("Udumbara", HuntRank.S, "Stormblood"),
        [5988] = new("Bone Crawler", HuntRank.S, "Stormblood"),
        [5989] = new("Salt and Light", HuntRank.S, "Stormblood"),
        [8656] = new("Domovoi", HuntRank.B, "Shadowbringers"),
        [8657] = new("Vulpangue", HuntRank.B, "Shadowbringers"),
        [8893] = new("Mindmaker", HuntRank.B, "Shadowbringers"),
        [8894] = new("Pachamama", HuntRank.B, "Shadowbringers"),
        [8898] = new("Gilshs Aath Swiftclaw", HuntRank.B, "Shadowbringers"),
        [8899] = new("Deacon", HuntRank.B, "Shadowbringers"),
        [8903] = new("Worm of the Well", HuntRank.B, "Shadowbringers"),
        [8904] = new("Juggler Hecatomb", HuntRank.B, "Shadowbringers"),
        [8908] = new("La Velue", HuntRank.B, "Shadowbringers"),
        [8909] = new("Itzpapalotl", HuntRank.B, "Shadowbringers"),
        [8913] = new("Coquecigrue", HuntRank.B, "Shadowbringers"),
        [8914] = new("Indomitable", HuntRank.B, "Shadowbringers"),
        [8653] = new("Aglaope", HuntRank.S, "Shadowbringers"),
        [8890] = new("Ixtab", HuntRank.S, "Shadowbringers"),
        [8895] = new("Gunitt", HuntRank.S, "Shadowbringers"),
        [8900] = new("Tarchia", HuntRank.S, "Shadowbringers"),
        [8905] = new("Tyger", HuntRank.S, "Shadowbringers"),
        [8910] = new("Forgiven Pedantry", HuntRank.S, "Shadowbringers"),
        [8915] = new("Forgiven Rebellion", HuntRank.S, "Shadowbringers"),
        [8916] = new("Forgiven Gossip", HuntRank.S, "Shadowbringers"),
        [10635] = new("Green Archon", HuntRank.B, "Endwalker"),
        [10636] = new("Ü-u-ü-u", HuntRank.B, "Endwalker"),
        [10637] = new("Vajrakumara", HuntRank.B, "Endwalker"),
        [10638] = new("Iravati", HuntRank.B, "Endwalker"),
        [10639] = new("Warmonger", HuntRank.B, "Endwalker"),
        [10640] = new("Emperor's Rose", HuntRank.B, "Endwalker"),
        [10641] = new("Daphnia Magna", HuntRank.B, "Endwalker"),
        [10642] = new("Genesis Rock", HuntRank.B, "Endwalker"),
        [10645] = new("Level Cheater", HuntRank.B, "Endwalker"),
        [10646] = new("Oskh Rhei", HuntRank.B, "Endwalker"),
        [10644] = new("Shockmaw", HuntRank.B, "Endwalker"),
        [10643] = new("Yumcax", HuntRank.B, "Endwalker"),
        [10619] = new("Armstrong", HuntRank.S, "Endwalker"),
        [10622] = new("Narrow-rift", HuntRank.S, "Endwalker"),
        [10621] = new("Ophioneus", HuntRank.S, "Endwalker"),
        [10620] = new("Ruminator", HuntRank.S, "Endwalker"),
        [10618] = new("Sphatika", HuntRank.S, "Endwalker"),
        [10617] = new("Burfurlur the Canny", HuntRank.S, "Endwalker"),
        [10615] = new("Ker", HuntRank.S, "Endwalker"),
        [10616] = new("Ker Shroud", HuntRank.S, "Endwalker"),
        [13144] = new("mad maguey", HuntRank.B, "Dawntrail"),
        [13145] = new("Chupacabra", HuntRank.B, "Dawntrail"),
        [13146] = new("the Slammer", HuntRank.B, "Dawntrail"),
        [13147] = new("go'ozoabek'be", HuntRank.B, "Dawntrail"),
        [13148] = new("Leafscourge Hadoll Ja", HuntRank.B, "Dawntrail"),
        [13149] = new("Xty'iinbek", HuntRank.B, "Dawntrail"),
        [13150] = new("nopalitender Fabuloso", HuntRank.B, "Dawntrail"),
        [13151] = new("Uktena", HuntRank.B, "Dawntrail"),
        [13152] = new("Gallowsbeak", HuntRank.B, "Dawntrail"),
        [13153] = new("gargant", HuntRank.B, "Dawntrail"),
        [13154] = new("jewel bearer", HuntRank.B, "Dawntrail"),
        [13155] = new("13th Child", HuntRank.B, "Dawntrail"),
        [13360] = new("Kirlirger the Abhorrent", HuntRank.S, "Dawntrail"),
        [13444] = new("Ihnuxokiy", HuntRank.S, "Dawntrail"),
        [12754] = new("Neyoozoteel", HuntRank.S, "Dawntrail"),
        [13399] = new("Sansheya", HuntRank.S, "Dawntrail"),
        [13156] = new("Atticus the Primogenitor", HuntRank.S, "Dawntrail"),
        [13437] = new("the Forecaster", HuntRank.S, "Dawntrail"),
        [13406] = new("arch aethereater", HuntRank.S, "Dawntrail"),
        [13407] = new("crystal incarnation", HuntRank.S, "Dawntrail"),
    };

    public static OtherRankMark? Lookup(uint nameId) =>
        ByNameId.TryGetValue(nameId, out var m) ? m : null;
}
